[3-1][번역][0.18.0]Getting Started/Choosing a web library
alstn2468/yew pull request #9
Opened 2021-09-12 11:58 UTC by bugoverdose

Description

[[3-1][번역][0.18.0]Getting Started/Choosing a web library](https://github.com/alstn2468/yew/projects/1#card-68497516)

2021-09-12 11:59 UTC, bugoverdose commented on website/i18n/ko/docusaurus-plugin-content-docs/version-0.18.0/getting-started/choose-web-library.md
> +      <td style={{ textAlign: "left" }}>문제 발생시 대체로 <code>Result</code> 대신 panic을 반환하고자 합니다. 예를 들어 <code>stdweb::web::window()</code>가 worker 내부에서 호출되면 panic이 발생합니다.</td>
Rust 문법 고려했을 대 이게 맞는 표현인지 아시는 분 있으면 피드백해주세요.

2021-09-12 12:01 UTC, bugoverdose commented on website/i18n/ko/docusaurus-plugin-content-docs/version-0.18.0/getting-started/choose-web-library.md
> +      <td style={{ textAlign: "left" }}>Rust API는 Web IDL 사양을 기반으로 생성됩니다.</td>
spec == 규격 vs 사양?

2021-09-12 13:40 UTC, ChobobDev commented on website/i18n/ko/docusaurus-plugin-content-docs/version-0.18.0/getting-started/choose-web-library.md
> +      <td style={{ textAlign: "left" }}>Rust API는 Web IDL 사양을 기반으로 생성됩니다.</td>
`사양`이 더 적합해 보이는거 같아요.

2021-09-13 15:01 UTC, devgony commented on website/i18n/ko/docusaurus-plugin-content-docs/version-0.18.0/getting-started/choose-web-library.md
> +      <td style={{ textAlign: "left" }}>문제 발생시 대체로 <code>Result</code> 대신 panic을 반환하고자 합니다. 예를 들어 <code>stdweb::web::window()</code>가 worker 내부에서 호출되면 panic이 발생합니다.</td>
갈구고싶었는데 공격 할 만한 부분이없어 아쉽군요... 문제 없는것같습니다...........
Rust는 conservative 한 에러 처리가 기본이기 때문에 모든 상황에 대해서 Result 를 씌워 Ok 혹은 Err 케이스에 대한 처리를 명확히 해야만 동작한대요. 그걸 뭉개기위해서는 .unwrap() 을 쓰는데 stdweb은 내부적으로는 그렇게 처리해서 panic을 일으키게 냅두나보네요..

2021-09-13 15:03 UTC, devgony approved these changes

2021-09-13 15:04 UTC, devgony requested changes
conflict 해결만 해주시면 될 것 같습니다.

2021-09-14 01:22 UTC, ChobobDev commented
LGTM

2021-09-14 01:28 UTC, ChobobDev approved these changes

2021-09-14 01:28 UTC, merged

2021-09-14 07:36 UTC, ChobobDev commented on website/i18n/ko/docusaurus-plugin-content-docs/version-0.18.0/getting-started/choose-web-library.md
> -      <td style={{ textAlign: "left" }}>Supported Targets</td>
Reference #14